# 머신러닝 기반 영화 리뷰 감성 분석
1. 데이터 준비 (전처리된 데이터 -> 특징 벡터 추출 (TF-IDF))
2. 머신러닝 모델별 학습 및 평가
3. 배포 준비 : 영화 리뷰 긍부정 판단 테스트 -> 클래스 생성, 모델 저장

## 1.데이터 준비 (전처리된 데이터)

In [1]:
import pandas as pd
data_filename = './data/Korean_movie_reviews_2016.csv'

# 데이터 로딩
review_df = pd.read_csv(data_filename)
review_df.head()

,review,label
0,부산 행 때문 너무 기대하고 봤,0
1,한국 좀비 영화 어색하지 않게 만들어졌 놀랍,1
2,조금 전 보고 왔 지루하다 언제 끝나 이 생각 드,0
3,평 밥 끼 먹자 돈 니 내고 미친 놈 정신사 좀 알 싶어 그래 밥 먹다 먹던 숟가락...,1
4,점수 대가 과 이 엑소 팬 어중간 점수 줄리 없겠 클레멘타인 이후 최고 평점 조작 ...,0


In [2]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165384 entries, 0 to 165383
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   review  165384 non-null  object
 1   label   165384 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 2.5+ MB


In [3]:
# 입력 데이터와 정답 데이터 추출
review_list = list(review_df.review)
label_list = list(review_df.label)

In [4]:
# 학습 데이터와 평가 데이터 분리
from sklearn.model_selection import train_test_split

train_X, test_X, train_Y, test_Y = train_test_split(review_list, label_list, test_size=0.2)
print(len(train_X), len(test_X), len(train_Y), len(test_Y))

132307 33077 132307 33077


## 2. 특징 벡터 추출 : TF-IDF

In [77]:
from konlpy.tag import Okt
# 한국어 감성 분석용 tokenizer 정의
def korean_tokenizer(text):
    my_tags = ['Noun', 'Adjective', 'Verb']
    my_stopwords = []
    return [word for word, tag in Okt().pos(text) if tag in my_tags and word not in my_stopwords]

In [78]:
# 최대 단어 수 1000개
# 학습 데이터로 Vectorizer 생성 및 학습 데이터 특징 벡터 추출
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(tokenizer=korean_tokenizer, max_features=1000)
vectorizer.fit(train_X)
print(len(vectorizer.get_feature_names_out()))

c:\Users\user\anaconda3\envs\aiservice26\lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


1000


In [ ]:
len(vectorizer.get_feature_names_out())

In [7]:
# 학습 데이터의 특징 벡터 추출
train_X_fv = vectorizer.transform(train_X)
print(train_X_fv.shape)
print(train_X_fv)

(132307, 1000)
  (np.int32(0), np.int32(770))	0.8536342522870949
  (np.int32(0), np.int32(861))	0.5208728859541956
  (np.int32(1), np.int32(241))	0.4855811630213191
  (np.int32(1), np.int32(629))	0.5969552650891036
  (np.int32(1), np.int32(771))	0.4835605973021839
  (np.int32(1), np.int32(885))	0.4171624315995109
  (np.int32(2), np.int32(41))	0.21086474092480761
  (np.int32(2), np.int32(103))	0.25065545593421995
  (np.int32(2), np.int32(159))	0.17479786086107676
  (np.int32(2), np.int32(201))	0.2421062766551602
  (np.int32(2), np.int32(254))	0.2738399360172755
  (np.int32(2), np.int32(284))	0.23123043466572873
  (np.int32(2), np.int32(406))	0.2008892453102766
  (np.int32(2), np.int32(412))	0.28106614974896993
  (np.int32(2), np.int32(458))	0.19034120524336362
  (np.int32(2), np.int32(544))	0.20126730857903377
  (np.int32(2), np.int32(626))	0.24780508807328683
  (np.int32(2), np.int32(719))	0.21561823987853204
  (np.int32(2), np.int32(794))	0.18910047419956325
  (np.int32(2), np.int32(9

In [8]:
train_X_fv.toarray()[:1]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [ ]:
# 테스트 데이터 특징 벡터 추출
test_X_fv = vectorizer.transform(test_X)
print(test_X_fv.shape)
print(test_X_fv)

  (np.int32(0), np.int32(197))	0.39161447999862325
  (np.int32(0), np.int32(293))	0.29934761202101634
  (np.int32(0), np.int32(393))	0.4894631944275103
  (np.int32(0), np.int32(885))	0.30735164822635974
  (np.int32(0), np.int32(887))	0.46901419900992664
  (np.int32(0), np.int32(933))	0.4505724503264233
  (np.int32(1), np.int32(93))	0.498236077138864
  (np.int32(1), np.int32(322))	0.38691227891591934
  (np.int32(1), np.int32(466))	0.4859299782332811
  (np.int32(1), np.int32(700))	0.4241000736925628
  (np.int32(1), np.int32(803))	0.43135934394600917
  (np.int32(2), np.int32(95))	0.5174439042074638
  (np.int32(2), np.int32(265))	0.5052961573998298
  (np.int32(2), np.int32(282))	0.4221138726522682
  (np.int32(2), np.int32(872))	0.45822625937877925
  (np.int32(2), np.int32(926))	0.297953306821287
  (np.int32(3), np.int32(83))	0.30589386732942975
  (np.int32(3), np.int32(392))	0.21920683211655734
  (np.int32(3), np.int32(474))	0.20336975934370394
  (np.int32(3), np.int32(567))	0.269775867145

In [10]:
# 정답 데이터 변환 (np.array)
import numpy as np
train_y = np.array(train_Y)
test_y = np.array(test_Y)

In [11]:
# 데이터 일부 확인
print(train_y[:10])
print(test_y[:10])

[1 1 0 1 0 0 1 1 1 0]
[1 0 0 1 1 1 1 1 1 0]


## 3. 머신러닝 모델별 학습 및 평가
* 의사결정 트리
* 랜덤포레스트
* 나이브 베이즈
* 로지스틱 회귀 분석
* SVM
* Perceptron

In [32]:
# 머신러닝 모델별 학습 성능 평가 결과 저장 준비
import pandas as pd
score_df = pd.DataFrame(columns=['train', 'test'])

## 3.1 의사결정 트리 (Decision Tree)

In [33]:
# 학습
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(train_X_fv, train_y)

DecisionTreeClassifier()

In [34]:
# 성능 평가
train_score = dtc.score(train_X_fv, train_y) * 100
print(train_score)
test_score = dtc.score(test_X_fv, test_y) * 100
print(test_score)

98.13993212755183
79.60214046013846


In [35]:
# 평가 결과 score_df에 추가
score_df.loc['DecisionTree'] = [train_score, test_score]
print(score_df)

                  train      test
DecisionTree  98.139932  79.60214


## 3.2 랜덤 포레스트 (Random Forrest)

In [36]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1)
rf.fit(train_X_fv, train_y)

RandomForestClassifier(n_jobs=-1)

In [37]:
train_score = rf.score(train_X_fv, train_y) * 100
test_score = rf.score(test_X_fv, test_y) * 100
print(train_score, test_score)

98.13690885591843 84.83236085497475


In [38]:
score_df.loc["RandomForest"] = [train_score, test_score]
print(score_df)

                  train       test
DecisionTree  98.139932  79.602140
RandomForest  98.136909  84.832361


## 3.3 나이브 베이즈 (Naive Baysian)

In [39]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(train_X_fv, train_y)

MultinomialNB()

In [40]:
train_score = mnb.score(train_X_fv, train_y) * 100
test_score = mnb.score(test_X_fv, test_y) * 100
print(train_score, test_score)

85.31370222286047 85.11049974302385


In [41]:
score_df.loc["NaiveBayes"] = [train_score, test_score]
print(score_df)

                  train       test
DecisionTree  98.139932  79.602140
RandomForest  98.136909  84.832361
NaiveBayes    85.313702  85.110500


## 3.4 로지스틱 회귀 분석 (Logistic Regression)

In [42]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver="liblinear")
lr.fit(train_X_fv, train_y)

LogisticRegression(solver='liblinear')

In [43]:
train_score = lr.score(train_X_fv, train_y) * 100
test_score = lr.score(test_X_fv, test_y) * 100
print(train_score, test_score)

86.20178826517116 85.8270097046286


In [44]:
score_df.loc["LogisticRegression"] = [train_score, test_score]
print(score_df)

                        train       test
DecisionTree        98.139932  79.602140
RandomForest        98.136909  84.832361
NaiveBayes          85.313702  85.110500
LogisticRegression  86.201788  85.827010


## 3.5 SVM (Support Vector Machine)

In [45]:
from sklearn.svm import LinearSVC

svc = LinearSVC(verbose=True)
svc.fit(train_X_fv, train_y)

[LibLinear]

LinearSVC(verbose=True)

In [46]:
train_score = svc.score(train_X_fv, train_y) * 100
test_score = svc.score(test_X_fv, test_y) * 100
print(train_score, test_score)

86.17079973092882 85.80887021192974


In [47]:
score_df.loc["SupportVectorMachine"] = [train_score, test_score]
print(score_df)

                          train       test
DecisionTree          98.139932  79.602140
RandomForest          98.136909  84.832361
NaiveBayes            85.313702  85.110500
LogisticRegression    86.201788  85.827010
SupportVectorMachine  86.170800  85.808870


## 3.6 Perceptron

In [48]:
from sklearn.linear_model import Perceptron

pc = Perceptron()
pc.fit(train_X_fv, train_y)

Perceptron()

In [49]:
train_score = pc.score(train_X_fv, train_y) * 100
test_score = pc.score(test_X_fv, test_y) * 100
print(train_score, test_score)

79.80001058145072 79.40865253801735


In [50]:
score_df.loc["Perceptron"] = [train_score, test_score]
print(score_df)

                          train       test
DecisionTree          98.139932  79.602140
RandomForest          98.136909  84.832361
NaiveBayes            85.313702  85.110500
LogisticRegression    86.201788  85.827010
SupportVectorMachine  86.170800  85.808870
Perceptron            79.800011  79.408653


## 3.7 성능 비교

In [51]:
# 평가 결과 저장 데이터 프레임 확인
print(score_df.sort_values(by="test", ascending=False))

                          train       test
LogisticRegression    86.201788  85.827010
SupportVectorMachine  86.170800  85.808870
NaiveBayes            85.313702  85.110500
RandomForest          98.136909  84.832361
DecisionTree          98.139932  79.602140
Perceptron            79.800011  79.408653


## 4. 영화 리뷰 긍부정 판단
* 학습된 모델 중 선택하여 활용

In [ ]:
# 영화 리뷰감성 분석용 tokenizer 정의
from konlpy.tag import Okt
def korean_tokenizer(text):
    my_tags = ['Noun', 'Adjective', 'Verb']
    my_stopwords = []
    return [word for word, tag in Okt().pos(text) if tag in my_tags and word not in my_stopwords]

# 특징 벡터 추출 모델 : vectorizer

# 학습 모델 선택
sa_model = lr

In [57]:
review = '영화가 재미있다'

# 텍스트 전처리

# 특징 벡터 추출
review_fv = vectorizer.transform([review])
# print(review_fv)

# 예측
pred = sa_model.predict(review_fv)
# print(pred)

# 예측 결과 출력
result = '긍정' if pred[0] >= 0.5 else '부정'
print(f'{review} -> {result}({pred[0]})')

영화가 재미있다 -> 긍정(1)


In [61]:
# 함수로 만들기
def analyze_sentiment(review):
    # 특징 벡터 추출
    review_fv = vectorizer.transform([review])

    # 학습된 모델로 예측
    pred = sa_model.predict(review_fv)

    # 예측값에 따라 결과를 생성하여 반환
    result = '긍정' if pred[0] >= 0.5 else '부정'
    return result, pred[0]

In [69]:
sa_model = svc
# 함수 테스트
reviews = [
    '이 영화 개꿀잼 ㅋㅋㅋ',
    '하품만 나온다',
    '이 영화 핵노잼 ㅠㅠ',
    '이딴게 영화냐 ㅉㅉ',
    '와 개쩐다',
    '감독 뭐하는 놈이냐',
    '정말 세계관 최강자들의 영화다'
]

for review in reviews:
    sentiment, prob = analyze_sentiment(review)
    print(f'{review} -> {sentiment}({prob})')

이 영화 개꿀잼 ㅋㅋㅋ -> 부정(0)
하품만 나온다 -> 긍정(1)
이 영화 핵노잼 ㅠㅠ -> 부정(0)
이딴게 영화냐 ㅉㅉ -> 부정(0)
와 개쩐다 -> 긍정(1)
감독 뭐하는 놈이냐 -> 부정(0)
정말 세계관 최강자들의 영화다 -> 긍정(1)


In [74]:
# 문장을 입력 받아서 긍부정 판단 
review = input('>> 리뷰 입력 : ')
sentiment, prob = analyze_sentiment(review)
print(f'{review} -> {sentiment}({prob})')

이게맞다 -> 부정(0)


In [ ]:
# 배포를 위한 모델 저장
import joblib

# 특징 추출용 vectorizer
joblib.dump(vectorizer, './model/sa_movie_vectorizer.pkl')

# 감성 분석 모델 sa_model
joblib.dump(sa_model, './model/sa_movie_predict.pkl')

['./model/sa_movie_predict.pkl']

In [ ]:
import joblib
def korean_tokenizer(text):
    my_tags = ['Noun', 'Adjective', 'Verb']
    my_stopwords = []
    return [word for word, tag in Okt().pos(text) if tag in my_tags and word not in my_stopwords]

class SentimentAnalyzer:
    def __init__(self, tokenizer,vectorizer_file, predict_model_file):
        self.__vectorizer = joblib.load(vectorizer_file)
        self.__predict_model = joblib.load(predict_model_file)
        self.__tokenizer = tokenizer
    
    def analyze_sentiment(self, review):
        # 특징 벡터 추출
        review_fv = self.__vectorizer.transform([review])

        # 학습된 모델로 예측
        pred = self.__predict_model.predict(review_fv)

        # 예측값에 따라 결과를 생성하여 반환
        result = '긍정' if pred[0] >= 0.5 else '부정'
        return result, pred[0]